[package]
name = "ufsc-thesis"
version = "0.1.3"
entrypoint = "lib.typ"
categories = [ "thesis", "layout" ]
disciplines = [ "engineering", "education" ]
description = "ABNT-compliant thesis and dissertations for works at UFSC"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = ""
